"""added user type - power user

Revision ID: d675094b30f2
Revises: be4c773c3105
Create Date: 2024-04-16 17:40:49.476599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd675094b30f2'
down_revision: Union[str, None] = 'be4c773c3105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userenum ADD VALUE 'POWER_USER'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userenum DROP VALUE 'POWER_USER'")
    # ### end Alembic commands ###
